baseURL: "https://YuXinFan.github.io"
languageCode: 'en-us'
title: '550X'
theme: "PaperMod"
publishDir: "docs"

enableRobotsTXT: true
enableInlineShortcodes: true
enableImageShortcodes: true

params:
    defaultTheme: auto
    ShowReadingTime : true
    homeInfoParams:
        Title: 550X's Blog
        Content: Meaningful blogs from me and others

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/YuXinFan"
        - name: "e-mail"
          url: "fanyx@shanghaitech.edu.cn"
    #     - name: "<platform 2>"
    #         url: "<link2>"
            
outputs:
    home: 
     - HTML
     - RSS
     - JSON # is necessary

TocOpen: true