baseURL: "https://YuXinFan.github.io"
languageCode: 'en-us'
title: 'My Website'
theme: "PaperMod"
publishDir: "docs"

enableRobotsTXT: true
enableInlineShortcodes: true
enableImageShortcodes: true

Params:
    ShowReadingTime : true

outputs:
    home: 
     - HTML
     - RSS
     - JSON # is necessary

TocOpen: true