baseURL: "https://YuXinFan.github.io"
languageCode: 'en-us'
title: '福岚溪森'
theme: "PaperMod"
publishDir: "docs"

enableRobotsTXT: true
enableInlineShortcodes: true
enableImageShortcodes: true

params:
    defaultTheme: auto
    ShowReadingTime : true
    homeInfoParams:
        Title: 福岚溪森's Blog
        Content: 生命的奇迹

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/fanyxok"
        - name: "e-mail"
          url: "xmsszycz@163.com"
    #     - name: "<platform 2>"
    #         url: "<link2>"
            
outputs:
    home: 
     - HTML
     - RSS
     - JSON # is necessary

TocOpen: true