baseURL: "https://YuXinFan.github.io"
languageCode: 'en-us'
title: 'My Website'
theme: "PaperMod"
publishDir: "docs"

enableRobotsTXT: true
enableInlineShortcodes: true
enableImageShortcodes: true

params:
    defaultTheme: auto
    ShowReadingTime : true
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...

    # socialIcons: # optional
    #     - name: "<platform>"
    #         url: "<link>"
    #     - name: "<platform 2>"
    #         url: "<link2>"
            
outputs:
    home: 
     - HTML
     - RSS
     - JSON # is necessary

TocOpen: true